name: Build QMK firmware
on:
  push:
    paths:
      - 'keyboards/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          path: my-repo

      - name: Disable git safe directory checks
        run : git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
          path: qmk_firmware

      - name: Checkout Vial
        uses: actions/checkout@v4
        with:
          repository: vial-kb/vial-qmk
          submodules: recursive
          path: vial-qmk

      - name: Copy keyboard definiitons from this repo into vial
        run: |
          cp -r my-repo/keyboards/* vial-qmk/keyboards/

      - name: Build firmware
        run: |
          cd vial-qmk
          qmk compile -kb keychron/q3/ansi_encoder -km vial

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: keychron_q3_fw_${{ github.run_number }}
          path: |
            vial-qmk/*.bin
            vial-qmk/*.hex
            vial-qmk/*.uf2
