name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    outputs:
      outdir: ${{ steps.save.outputs.outdir }}

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          path: my-repo

      - name: Disable git safe directory checks
        run : git config --global --add safe.directory '*'

      - name: Checkout QMK
        uses: actions/checkout@v4
        with:
          repository: qmk/qmk_firmware
          submodules: recursive
          path: qmk_firmware

      - name: Checkout Vial
        uses: actions/checkout@v4
        with:
          repository: vial-kb/vial-qmk
          submodules: recursive
          path: vial-qmk

      - name: Copy keyboard definiitons from this repo into vial
        run: |
          cp -rT my-repo/* vial-qmk/keyboards/

      - name: Build firmware
        run: |
          cd vial-qmk
          qmk compile -kb keychron/q3/ansi_encoder -km vial

      - name: Save firmware to shared directory
        id: save
        run: |
          mkdir -p /github/workspace/output
          cd vial-qmk
          mv *.hex *.bin *.uf2 /github/workspace/output || true
          echo "outdir=output" >> "$GITHUB_OUTPUT"

  upload:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: keychron_q3_fw
          path: output
