name: Build QMK firmware
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli

    steps:

    - name: Checkout current repo
      uses: actions/checkout@v4

    - name: Disable git safe directory checks
      run : git config --global --add safe.directory '*'

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
        path: qmk_firmware

    - name: Checkout Vial
      uses: actions/checkout@v3
      with:
        repository: vial-kb/vial-qmk
        submodules: recursive
        path: vial-qmk

    - name: Copy keyboard definiitons from this repo into vial
      run: |
        cp -rT . vial-qmk/keyboards/

    - name: Build firmware
      run: qmk compile -kb keychron/q3/ansi_encoder -km vial

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: keychron_q3_fw
        path: |
          *.hex
          *.bin
          *.uf2